# -*- coding: utf-8 -*-
"""EMG_Proc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AsnqH1sz0c57CN6rkJ8KLeFlu3wijhJ7

Las unidades motoras son el conjunto de una neuronas motora (que transmite la señal nerviosa) y todas las fibras musculares que esa neurona controla. Los músculos están compuestos por unidades motoras de diferentes tamaños y capacidades, que se reclutan en función de la intensidad del esfuerzo muscular.

Cada unidad motora tiene una frecuencia de activación preferida o frecuencia de disparo que depende de ciertos factores, como su tamaño, tipo (lenta o rápida) y la naturaleza de la contracción muscular. Esto tiene que ver con el proceso de reclutamiento de unidades motoras y cómo el sistema nervioso las utiliza durante diferentes niveles de esfuerzo.

Existen dos tipos de unidades motoras principales:

* Unidades motoras de **tipo I** (lentas, de contracción larga y baja fatiga): Estas unidades motoras se reclutan en situaciones de baja intensidad y esfuerzo prolongado, como cuando realizas una caminata o una actividad de resistencia. Estas unidades tienen una frecuencia de disparo baja y pueden generar frecuencias más bajas en el espectro de la señal EMG (alrededor de **5-20 Hz**, por ejemplo).
* Unidades motoras de **tipo II** (rápidas, de contracción explosiva y alta fatiga): Son reclutadas durante esfuerzos más intensos y rápidos, como en levantamientos de pesas o sprints. Estas unidades motoras tienden a tener una frecuencia de disparo alta y producen frecuencias más altas en el espectro de la señal EMG (**por encima de 50 Hz**).

Cuando se realiza una contracción muscular, el sistema nervioso recluta primero las unidades motoras más pequeñas y lentas (tipo I), ya que estas requieren menos energía para activarse. A medida que la contracción se vuelve más intensa, el sistema nervioso recluta unidades motoras más grandes y más rápidas (tipo II), que son capaces de generar más fuerza, pero también se fatigan más rápido.

El proceso de reclutamiento está relacionado con la frecuencia a la que las unidades motoras disparan sus impulsos eléctricos. A medida que aumenta la intensidad del esfuerzo, el nervio motriz dispara más frecuentemente las unidades motoras de tipo II, lo que se traduce en un aumento de la frecuencia en la señal EMG.

En resumen:
* Ejercicio aeróbico prolongado (como correr a ritmo moderado durante 30 minutos):
  *  Análisis en el tiempo: Verías una señal con baja amplitud, ya que la intensidad del esfuerzo es relativamente constante.
  * Análisis en la frecuencia: Verías frecuencias bajas o medias (más unidades motoras lentas), indicando que el esfuerzo es de baja a moderada intensidad, reclutando principalmente unidades motoras tipo I (lentas).
* Ejercicio anaeróbico de alta intensidad (como hacer sprints o levantar pesas):
  * Análisis en el tiempo: Verías una señal con alta amplitud, debido a los picos de fuerza en momentos específicos.
  * Análisis en la frecuencia: Verías frecuencias más altas, ya que se reclutan unidades motoras tipo II (rápidas), lo que indica que el esfuerzo es explosivo y de alta intensidad.
"""

!git clone https://github.com/crisurdiales/EMG-Signal-Processing-Library

#añadir la ruta al sistema para poder acceder al codigo
import sys
sys.path.append('/content/EMG-Signal-Processing-Library/Python')

import signal_utilities as su
import emg
#EMG_filter_basic:
#Rectificación: Convierte valores negativos en positivos.
#Filtro de media móvil (Moving Average): Suaviza la señal.
#Opción de filtro de paso bajo (Low Pass Filter) si reference_available=True.

#EMG_filter (hereda de EMG_filter_basic):
#Añade filtrado para eliminar ruido de baja frecuencia.
#Normaliza la señal considerando valores neutros calculados por PkPk.

import pandas as pd
import matplotlib.pyplot as plt

# Cargar datos desde el CSV
data_path = '/content/EMG-Signal-Processing-Library/Sample Signals/emgvalues_1.csv'
emg_data_1 = pd.read_csv(data_path, header=None).squeeze()  # Convierte el DataFrame en Serie
data_path = '/content/EMG-Signal-Processing-Library/Sample Signals/emgvalues_2.csv'
emg_data_2 = pd.read_csv(data_path, header=None).squeeze()
data_path = '/content/EMG-Signal-Processing-Library/Sample Signals/emgvalues_3.csv'
emg_data_3 = pd.read_csv(data_path, header=None).squeeze()

fs = 1000  # Hz, frecuencia de muestreo del EMG que usamos

"""Parámetros del filtro a crear:


*   sample_frequency_ frecuencia del EMG en Hz
*   range_ número de puntos para calcular la media movil en segundos (entre 0.2 y 0.5)
*   min_EMG_frequency_ mínimo valor de frecuencua por debajo del cual se eliminan las muestras (40 está bien)
*  max_EMG_frequency lo mismo, pero para alta frecuencia. 150 está bien
* remove_low_frequency Si el sensor ya filtra, pues nada, si no, recomendable. Puede ser HIGH_PASS_FILTER_ON o HIGH_PASS_FILTER_OFF
* reference_available indica si tenemos alguna señal de referencia. Puede ser REFERENCE_AVAILABLE or REFERENCE_UNAVAILABLE


"""

# Crear filtro básico con frecuencia de muestreo de 200 Hz y ventana de 0.1 segundos
basic_filter = emg.EMG_filter_basic(sample_frequency=fs, range_=0.1, reference_available=False)
# Crear filtro avanzado con parámetros personalizados
emg_filter = emg.EMG_filter(sample_frequency=fs, range_=0.5, min_EMG_frequency=25, max_EMG_frequency=300, reference_available=False)

#filtramos la señal
# Filtrar la señal usando el filtro avanzado
filtered_signal_1 = [emg_filter.filter(value) for value in emg_data_1]
filtered_signal_2 = [emg_filter.filter(value) for value in emg_data_2]
filtered_signal_3 = [emg_filter.filter(value) for value in emg_data_3]

# Configurar el eje temporal
time = [i / fs for i in range(len(emg_data_1))]

# Graficar señal original vs filtrada
plt.figure(figsize=(15, 6))
plt.plot(time, emg_data_1, label='Señal Original', alpha=0.5)
plt.plot(time, filtered_signal_1, label='Señal Filtrada', linewidth=2)
plt.title("Filtrado de Señal EMG")
plt.xlabel("Tiempo (s)")
plt.ylabel("Amplitud (mV)")
plt.legend()
plt.grid(True)
plt.show()

"""Ahora que la señal está filtrada, se pueden escoger las métricas que se deseen para el estudio:

Objetivo->Métricas recomendadas

*   **Medir fuerza muscular**->RMS, MAV, ARV
*   **Detectar fatiga**->MNF, MDF, ZC
*   **Analizar rapidez de contracción**->Pk-Pk, SSC
*   **Control de prótesis**	->RMS, MAV, ZC
*   **Estudios clínicos**->Entropía, MNF, MDF

Principales métricas extra en EMG y su relevancia:

1.   **RMS** (Root Mean Square)
Qué es: La raíz cuadrada de la media de las señales al cuadrado.
Por qué importa:
Proporciona una medida de la intensidad muscular.
Se correlaciona bien con la fuerza generada durante contracciones isométricas.
🧩 Útil para: Evaluar esfuerzos musculares, comparando niveles de activación entre tareas.
2.   **MAV** (Mean Absolute Value)
Qué es: Promedio de los valores absolutos de la señal EMG.
Por qué importa:
Similar al RMS pero más simple computacionalmente.
Refleja la actividad general del músculo.
🧩 Útil para: Seguimiento de patrones de activación durante movimientos dinámicos.
3.   **Pk-Pk** (Peak-to-Peak Amplitude)
Qué es: Diferencia entre el pico máximo y mínimo en un intervalo.
Por qué importa:
Indica la variabilidad y amplitud de la señal.
Ayuda a detectar contracciones repentinas o espasmos.
🧩 Útil para: Estudios de reflejos musculares y respuesta rápida a estímulos.
4.   **MNF** (Mean Frequency) y **MDF** (Median Frequency)
Qué son:
MNF: Promedio de las frecuencias en el espectro.
MDF: Frecuencia que divide el espectro en dos áreas iguales.
Por qué importan:
Son indicadores clave de fatiga muscular.
Durante la fatiga, estas frecuencias suelen desplazarse hacia valores más bajos.
🧩 Útil para: Monitoreo de la resistencia muscular durante ejercicios prolongados.
5.   **ZC** (Zero Crossing)
Qué es: Número de veces que la señal cruza el eje cero.
Por qué importa:
Se relaciona con la frecuencia y complejidad de la señal.
Puede indicar variaciones en la activación motora.
🧩 Útil para: Diferenciar tipos de movimientos o niveles de esfuerzo.
6.   **SSC** (Slope Sign Changes)
Qué es: Número de veces que cambia la pendiente de la señal.
Por qué importa:
Refleja la dinámica de la contracción muscular.
Útil para detectar movimientos rápidos o vibraciones musculares.
🧩 Útil para: Análisis de actividades deportivas o tareas de precisión.
7.   **ARV** (Average Rectified Value)
Qué es: Promedio de la señal rectificada.
Por qué importa:
Similar al MAV, representa la energía de la señal.
🧩 Útil para: Estudios clínicos donde la simplicidad es clave.
8.   **Entropía y medidas no lineales**
Qué es: Cálculo de la complejidad y aleatoriedad de la señal.
Por qué importa:
Permite detectar alteraciones neuromusculares o temblores patológicos.
🧩 Útil para: Diagnóstico médico y control de prótesis mioeléctricas.
"""

import numpy as np
# Funciones para calcular las métricas

# 1. RMS
def calculate_rms(signal):
    return np.sqrt(np.mean(np.square(signal)))

# 2. MAV
def calculate_mav(signal):
    return np.mean(np.abs(signal))

# 3. ARV
def calculate_arv(signal):
    return np.mean(np.abs(signal))

# 4. ZC (Zero Crossing)
def calculate_zc(signal):
    zero_crossings = np.where(np.diff(np.sign(signal)))[0]
    return len(zero_crossings)

# Calcular todas las métricas
rms = calculate_rms(filtered_signal_1)
mav = calculate_mav(filtered_signal_1)
arv = calculate_arv(filtered_signal_1)
zc = calculate_zc(filtered_signal_1)

# Mostrar los resultados
print(f'RMS: {rms}')
print(f'MAV: {mav}')
print(f'ARV: {arv}')
print(f'Zero Crossings: {zc}')

"""* RMS (magnitud de la señal EMG; se centra en su energía) para tareas no fatigosas suele estar entre 1 y 10. 33 sugiere una contracción fuerte.
* MAV (promedio de magnitud de la señal), de nuevo, lo normal en reposo entre 1 y 10. 29 es muy alto (RMS es más preciso, en cualquier caso).
* ARV tiene sentido sólo si vamos a enventanar la señal, de hecho el sumatorio va entre i e i+j. Si usamos la señal completa, es igual a MAV
*  Zero crossings es lo obvio: cuantas veces corta el eje. En contracciones dinámicas (como cuando se mueve una extremidad o el músculo cambia su longitud), los Zero Crossings aumentan, ya que el músculo está alternando entre contracción y relajación (o distensión). A medida que un músculo se fatiga, puede haber menos alternancia en las contracciones y relajaciones, lo que puede reducir el número de cruces por cero, indicando una menor dinámica muscular. Zero Crossing no necesariamente indica activación de un músculo antagonista; también puede ser simplemente el paso de contracción a relajación del mismo músculo.
"""

# 5. MNF y MDF
def calculate_mnf_mdf(signal, fs):
    # Realizamos la FFT de la señal
    n = len(signal)
    freqs = np.fft.fftfreq(n, 1/fs)
    fft_signal = np.fft.fft(signal)

    # Calculamos el espectro de potencia
    power_spectrum = np.abs(fft_signal)**2

    # Filtramos las frecuencias negativas
    # Create a mask for positive frequencies with the original length
    mask = freqs > 0

    # Apply the mask to both frequencies and power spectrum
    freqs = freqs[mask]
    power_spectrum = power_spectrum[mask]

    # Calculamos MNF y MDF
    mnf = np.sum(freqs * power_spectrum) / np.sum(power_spectrum)
    mdf = freqs[np.cumsum(power_spectrum) >= np.sum(power_spectrum) / 2][0]

    return mnf, mdf

# 6. PKF (Peak Frequency)
def calculate_pkf(signal, fs):
    # Realizamos la FFT de la señal
    n = len(signal)
    freqs = np.fft.fftfreq(n, 1/fs)
    fft_signal = np.fft.fft(signal)

    # Calculamos el espectro de potencia
    power_spectrum = np.abs(fft_signal)**2

    # Filtramos las frecuencias negativas
    # Create a mask for positive frequencies with the original length
    mask = freqs > 0

    # Apply the mask to both frequencies and power spectrum
    freqs = freqs[mask]
    power_spectrum = power_spectrum[mask]

    # Encontramos la frecuencia de pico
    pkf = freqs[np.argmax(power_spectrum)]

    return pkf

# Calcular todas las métricas

mnf, mdf = calculate_mnf_mdf(filtered_signal_1, fs)
pkf = calculate_pkf(filtered_signal_1, fs)

# Mostrar los resultados

print(f'MNF: {mnf} Hz')
print(f'MDF: {mdf} Hz')
print(f'Peak Frequency (PKF): {pkf} Hz')

metricas_df = pd.DataFrame(index=['filtered_signal_1', 'filtered_signal_2', 'filtered_signal_3'],
                          columns=['RMS', 'MAV', 'ARV', 'ZC', 'MNF', 'MDF', 'PKF'])

# Calcular métricas para cada señal y guardar en el DataFrame
for i, signal in enumerate([filtered_signal_1, filtered_signal_2, filtered_signal_3]):
  metricas_df.loc[f'filtered_signal_{i+1}', 'RMS'] = calculate_rms(signal)
  metricas_df.loc[f'filtered_signal_{i+1}', 'MAV'] = calculate_mav(signal)
  metricas_df.loc[f'filtered_signal_{i+1}', 'ARV'] = calculate_arv(signal)
  metricas_df.loc[f'filtered_signal_{i+1}', 'ZC'] = calculate_zc(signal)
  metricas_df.loc[f'filtered_signal_{i+1}', 'MNF'], metricas_df.loc[f'filtered_signal_{i+1}', 'MDF'] = calculate_mnf_mdf(signal, fs)
  metricas_df.loc[f'filtered_signal_{i+1}', 'PKF'] = calculate_pkf(signal, fs)

# Mostrar el DataFrame
metricas_df

"""* MNF Es la frecuencia en la que se concentra el grueso de la energía espectral (ojo, es media ponderada). 1.28 indica que la frecuencia central de la señal EMG está muy baja, lo que generalmente está asociado con contracciones musculares lentas o de baja intensidad. En estos estados las unidades motoras de bajo umbral (que son más lentas) están activas y dominan la señal. También en caso de fatiga, el músculo comienza a reclutar unidades motoras de bajo umbral (músculos de contracción más lenta) para mantener la actividad muscular, lo que provoca que la frecuencia de la señal EMG baje. A ritmo moderado nos metemos en 10 Hz y 20 Hz. Hasta 50 Hz ya estamos en modo HIT/sprint. Sensible a picos de energía.
* MDF es una frecuencia mediana en el espectro de la señal EMG que refleja la distribución general de la energía en las frecuencias de la señal (se toma el peso de cada frecuencia según su contribución a la energía total y se calcula un promedio de esas frecuencias). Los rangos son también menos de 10 Hz, entre 10 y 20 y más de 20. 0.58 es muy bajo, significa lo mismo de antes. Menos sensible a picos y más a las frecuencias dominantes.
* PKF es el punto donde el espectro de potencia alcanza su máximo. Es particularmente útil en tareas de esfuerzo de corta duración y alta intensidad, como movimientos explosivos, esfuerzos de potencia, o contracciones rápidas.  No está tan influenciado por las frecuencias bajas, sino que se concentra más en picos específicos, lo cual es muy útil para tareas que requieren detectar patrones específicos de frecuencia.
"""

# Graficar las métricas junto con la señal
plt.figure(figsize=(12, 6))

# Graficar señal filtrada
plt.subplot(2, 1, 1)
plt.plot(filtered_signal_2, label='Señal Filtrada')
plt.title("Señal Filtrada EMG")
plt.xlabel("Tiempo (muestras)")
plt.ylabel("Amplitud")

# Graficar espectro de frecuencias
plt.subplot(2, 1, 2)
n = len(filtered_signal_2)
frequencies = np.fft.fftfreq(n, 1/fs)
fft_vals = np.fft.fft(filtered_signal_2)
plt.plot(frequencies[:n//2], np.abs(fft_vals)[:n//2])
plt.title("Espectro de Frecuencia de la Señal")
plt.xlabel("Frecuencia (Hz)")
plt.ylabel("Amplitud")

plt.tight_layout()
plt.show()

# Define la figura y los ejes en una matriz de 2x3
fig, axs = plt.subplots(2, 3, figsize=(18, 10))

# Lista de señales filtradas
filtered_signals = [filtered_signal_1, filtered_signal_2, filtered_signal_3]

# Itera sobre las señales para graficarlas y sus espectros
for i, signal in enumerate(filtered_signals):
    # Graficar la señal en la primera fila
    axs[0, i].plot(signal, label=f'Señal Filtrada {i+1}')
    axs[0, i].set_title(f"Señal Filtrada EMG {i+1}")
    axs[0, i].set_xlabel("Tiempo (muestras)")
    axs[0, i].set_ylabel("Amplitud")

    # Calcular y graficar el espectro de frecuencias en la segunda fila
    n = len(signal)
    frequencies = np.fft.fftfreq(n, 1/fs)
    fft_vals = np.fft.fft(signal)
    axs[1, i].plot(frequencies[:n//2], np.abs(fft_vals)[:n//2])
    axs[1, i].set_title(f"Espectro de Frecuencia {i+1}")
    axs[1, i].set_xlabel("Frecuencia (Hz)")
    axs[1, i].set_ylabel("Amplitud")
    # Set x-axis limits to 0-50 Hz
    axs[1, i].set_xlim(0, 5)

# Ajusta el espaciado entre los subplots y muestra la figura
plt.tight_layout()
plt.show()